/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.eklezia;

/**
 *
 * @author karma03
 */
public class Paccueil extends javax.swing.JFrame {

    /**
     * Creates new form Paccueil
     */
    public Paccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnconnexion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panmenu = new javax.swing.JPanel();
        ppancinq = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ppanquatre = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ppantrois = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ppanun = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ppandeux = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnconnexion.setBackground(new java.awt.Color(255, 255, 255));
        btnconnexion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnconnexion.setForeground(new java.awt.Color(124, 69, 17));
        btnconnexion.setText("Se Deconnecter");
        btnconnexion.setBorderPainted(false);
        btnconnexion.setFocusPainted(false);
        btnconnexion.setFocusable(false);
        btnconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(btnconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(124, 69, 17));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_cancel_16.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eglise Saint-Potache--System de gestion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(944, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(511, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 40));

        panmenu.setBackground(new java.awt.Color(124, 69, 17));
        panmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ppancinq.setBackground(new java.awt.Color(124, 69, 17));
        ppancinq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_cash_in_hand_32.png"))); // NOI18N
        jLabel6.setText("CATEGORIE DEPENSE");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        ppancinq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 40));

        panmenu.add(ppancinq, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 260, 60));

        ppanquatre.setBackground(new java.awt.Color(124, 69, 17));
        ppanquatre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_recieve_32.png"))); // NOI18N
        jLabel5.setText("CATEGORIE RECETTE");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        ppanquatre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        panmenu.add(ppanquatre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 60));

        ppantrois.setBackground(new java.awt.Color(124, 69, 17));
        ppantrois.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_donation_32.png"))); // NOI18N
        jLabel4.setText("DEPENSES");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        ppantrois.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        panmenu.add(ppantrois, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 60));

        ppanun.setBackground(new java.awt.Color(198, 144, 93));
        ppanun.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));
        ppanun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_home_32.png"))); // NOI18N
        jLabel2.setText("  ACCUEIL");
        ppanun.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        panmenu.add(ppanun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 60));

        ppandeux.setBackground(new java.awt.Color(124, 69, 17));
        ppandeux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_receive_dollar_32.png"))); // NOI18N
        jLabel3.setText("RECETTES");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        ppandeux.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        panmenu.add(ppandeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 60));

        getContentPane().add(panmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, 990, 70));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Que Dieu Vous benisse");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 570, 220));

        jLabel1.setBackground(new java.awt.Color(124, 69, 17));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/SmartSelect_20220407-093006_Opera Mini.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, -1, 570));

        setSize(new java.awt.Dimension(969, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Pconnexion access = new Pconnexion();
       access.quit();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Paccueil.super.dispose();
        Precettes open  = new Precettes();
        open.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Paccueil.super.dispose();
        Pdepenses open  = new Pdepenses();
        open.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Paccueil.super.dispose();
        PCrecettes open  = new PCrecettes();
        open.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Paccueil.super.dispose();
        PCdepenses open = new PCdepenses();
        open.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconnexionActionPerformed
        Paccueil.super.dispose();
        Pconnexion open = new Pconnexion();
        open.setVisible(true);
    }//GEN-LAST:event_btnconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panmenu;
    private javax.swing.JPanel ppancinq;
    private javax.swing.JPanel ppandeux;
    private javax.swing.JPanel ppanquatre;
    private javax.swing.JPanel ppantrois;
    private javax.swing.JPanel ppanun;
    // End of variables declaration//GEN-END:variables
}
