/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.eklezia;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karma03
 */
public class PCdepenses extends javax.swing.JFrame {

    /**
     * Creates new form Paccueil
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel rmodel = new DefaultTableModel();
    public PCdepenses() {
        initComponents();
     rmodel.addColumn("Id");
     rmodel.addColumn("Designation");
     rtable.setRowHeight(30);
     rtable.setShowGrid(true);
     rtable.setGridColor(new Color(124,69,17));
     rtable.setSelectionBackground(new Color(124,69,17));
     try
     {
     stm = conn.obtenirconnexion().createStatement();
     ResultSet Rs = stm.executeQuery("Select * from categoriesortie");
     while(Rs.next())
     {
     rmodel.addRow(new Object[]
     {
     Rs.getString("id"),
     Rs.getString("designation")
     });
     }
     }
     catch(Exception e)
     {
     System.err.println(e);
     }
     rtable.setModel(rmodel);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    private void rajouter()
{
        String id = txtid.getText();
        String ladesignation = txtdesignation.getText();
        String requete = "insert into categoriesortie(designation) VALUES ('"+
        ladesignation+"')";
        try
        {
            stm = conn.obtenirconnexion().createStatement();
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Categorie Ajoutee");
        }
        catch(SQLException | HeadlessException ex){JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());}
        rafficher();
}
     private void rdeplace(int i)
{
   try
   {
     txtid.setText(rmodel.getValueAt(i, 0).toString());
     txtdesignation.setText(rmodel.getValueAt(i, 1).toString());
   }
   catch(Exception e)
   {
       System.err.println(e);
       JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
   }
}
     private void rafficher()
{
 try
        {
        rmodel.setRowCount(0);
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from categoriesortie");
        while(Rs.next())
        {
            rmodel.addRow(new Object[]{Rs.getString("id"),
            Rs.getString("designation"),});
        }
        rrefresh();
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
        rtable.setModel(rmodel);
}
    private void rmodifier()
{
    try
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","Modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        {
            stm.executeUpdate("UPDATE categoriesortie SET designation='"
                    +txtdesignation.getText()+
                    "' WHERE id="+txtid.getText());
            rafficher();
            rrefresh();
        }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Erreur de modification"+e.getMessage());
            System.err.println(e);
            rafficher();
        }
}
    private void rrefresh()
{
            txtid.setText("");
            txtdesignation.setText("");
}
    private void rsupprimer()
    {
        try
        {
            if(JOptionPane.showConfirmDialog(null, "Attention, vous etes sur le point de supprimer cette cattegorie", "Supprimer la categorie", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            if(txtid.getText().length()!=0)
            {
                stm.executeUpdate("Delete From categoriesortie where id = "+txtid.getText());
                rafficher();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Veuillez remplir le champ id svp!!");
                rrefresh();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erreur de suppression"+e.getMessage());
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panbtn = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        panfiels = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtdesignation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panmenu = new javax.swing.JPanel();
        ppancinq = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ppanquatre = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ppantrois = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ppanun = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ppandeux = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panbtn.setBackground(new java.awt.Color(124, 69, 17));

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_add_32.png"))); // NOI18N
        add.setText("AJOUTER");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_edit_pie_chart_report_32.png"))); // NOI18N
        change.setText("MODIFIER");
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMouseClicked(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_trash_32.png"))); // NOI18N
        delete.setText("SUPPRIMER");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_update_left_rotation_32.png"))); // NOI18N
        refresh.setText("ACTUALISER");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panbtnLayout = new javax.swing.GroupLayout(panbtn);
        panbtn.setLayout(panbtnLayout);
        panbtnLayout.setHorizontalGroup(
            panbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnLayout.createSequentialGroup()
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panbtnLayout.setVerticalGroup(
            panbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 490, 70));

        panfiels.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(124, 69, 17));
        jLabel10.setText("ID");

        txtid.setEditable(false);

        txtdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesignationActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(124, 69, 17));
        jLabel13.setText("DESIGNATION");

        javax.swing.GroupLayout panfielsLayout = new javax.swing.GroupLayout(panfiels);
        panfiels.setLayout(panfielsLayout);
        panfielsLayout.setHorizontalGroup(
            panfielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panfielsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panfielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panfielsLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 290, Short.MAX_VALUE))
                    .addComponent(txtdesignation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panfielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        panfielsLayout.setVerticalGroup(
            panfielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panfielsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panfielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(panfielsLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panfielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(panfiels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 490, 90));

        jPanel1.setBackground(new java.awt.Color(124, 69, 17));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_cancel_16.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eglise Saint-Potache--System de gestion");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CATEGORIE DEPENSES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(235, 235, 235)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 40));

        panmenu.setBackground(new java.awt.Color(124, 69, 17));
        panmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ppancinq.setBackground(new java.awt.Color(198, 144, 93));
        ppancinq.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));
        ppancinq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_cash_in_hand_32.png"))); // NOI18N
        jLabel6.setText("CATEGORIE DEPENSE");
        ppancinq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 40));

        panmenu.add(ppancinq, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 260, 60));

        ppanquatre.setBackground(new java.awt.Color(124, 69, 17));
        ppanquatre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_recieve_32.png"))); // NOI18N
        jLabel5.setText("CATEGORIE RECETTE");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        ppanquatre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        panmenu.add(ppanquatre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 60));

        ppantrois.setBackground(new java.awt.Color(124, 69, 17));
        ppantrois.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_donation_32.png"))); // NOI18N
        jLabel4.setText("DEPENSES");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        ppantrois.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        panmenu.add(ppantrois, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 60));

        ppanun.setBackground(new java.awt.Color(124, 69, 17));
        ppanun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_home_32.png"))); // NOI18N
        jLabel2.setText("  ACCUEIL");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        ppanun.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        panmenu.add(ppanun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 60));

        ppandeux.setBackground(new java.awt.Color(124, 69, 17));
        ppandeux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_receive_dollar_32.png"))); // NOI18N
        jLabel3.setText("RECETTES");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        ppandeux.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        panmenu.add(ppandeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 60));

        getContentPane().add(panmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, 990, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/page2_img2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, 190));

        rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 440, 170));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/page4_img5.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 290, 190));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/page2_img2.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, 190));

        jLabel1.setBackground(new java.awt.Color(124, 69, 17));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/SmartSelect_20220407-093006_Opera Mini.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, -1, 570));

        setSize(new java.awt.Dimension(969, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Pconnexion access = new Pconnexion();
       access.quit();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       PCdepenses.super.dispose();
       Precettes open = new Precettes();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       PCdepenses.super.dispose();
       Paccueil open = new Paccueil();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void rtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtableMouseClicked
        try
        {
            int i=rtable.getSelectedRow();rdeplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_rtableMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
          // TODO add your handling code here:
        rajouter();
        rafficher();
        rrefresh();
    }//GEN-LAST:event_addMouseClicked

    private void changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseClicked
        // TODO add your handling code here:
        rmodifier();
        rafficher();
        rrefresh();
    }//GEN-LAST:event_changeMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        rsupprimer();
        rafficher();
        rrefresh();
    }//GEN-LAST:event_deleteMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        rrefresh();
    }//GEN-LAST:event_refreshMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       PCdepenses.super.dispose();
       Pdepenses open  = new Pdepenses();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesignationActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       PCdepenses.super.dispose();
       PCrecettes open = new PCrecettes();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PCdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PCdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PCdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PCdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PCdepenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel change;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panbtn;
    private javax.swing.JPanel panfiels;
    private javax.swing.JPanel panmenu;
    private javax.swing.JPanel ppancinq;
    private javax.swing.JPanel ppandeux;
    private javax.swing.JPanel ppanquatre;
    private javax.swing.JPanel ppantrois;
    private javax.swing.JPanel ppanun;
    private javax.swing.JLabel refresh;
    private javax.swing.JTable rtable;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
