/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.eklezia;

/**
 *
 * @author karma03
 */
public class Pchargement extends javax.swing.JFrame {

    /**
     * Creates new form Pchargement
     */
    public Pchargement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcount = new javax.swing.JLabel();
        txtchange = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtcount.setForeground(new java.awt.Color(255, 255, 255));
        txtcount.setText("0");
        getContentPane().add(txtcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 90, 43));

        txtchange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtchange.setForeground(new java.awt.Color(255, 255, 255));
        txtchange.setText("Jesus is coming soon");
        getContentPane().add(txtchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 420, 43));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 69, 17));
        jLabel3.setText("EGLISE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 43));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(124, 69, 17));
        jLabel6.setText("SAINT-POTACHE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/IMG_1153.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -5, 640, 470));
        getContentPane().add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        setSize(new java.awt.Dimension(601, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pchargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pchargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pchargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pchargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Pchargement well = new Pchargement();
        well.setVisible(true);
        well.setOpacity((float) 0.9);
        
        try
        {
            for (int i = 1; i <= 100; i++)
            {
                Thread.sleep(90);
                well.progressbar.setValue(i);
                if(i==0)
                {
                    well.txtchange.setText(""+"Jesus is coming soon...");
                }
                else if(i==20)
                {
                    well.txtchange.setText(""+"In God we trust...");
                }
                else if(i==40)
                {
                    well.txtchange.setText(""+"Jesus the King of Kings...");
                }
                else if(i==60)
                {
                    well.txtchange.setText(""+"We believe in God...");
                }
                else if(i==80)
                {
                    well.txtchange.setText(""+"He is the lord...");
                }
                else if(i==95)
                {
                    well.txtchange.setText(""+"Forgive us our debs...");
                }
                well.txtcount.setText(""+i+" %");
            }
        }
        catch (Exception e)
        { 
            System.err.println(e);
        }
        Pconnexion open = new Pconnexion();
        well.setVisible(false);
        open.setVisible(true);
        well.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JLabel txtchange;
    private javax.swing.JLabel txtcount;
    // End of variables declaration//GEN-END:variables
}
