/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.eklezia;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karma03
 */
public class Pdepenses extends javax.swing.JFrame {

    /**
     * Creates new form Paccueil
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel rmodel = new DefaultTableModel();
    public Pdepenses() {
        initComponents();
     rmodel.addColumn("Id");
     rmodel.addColumn("Montant");
     rmodel.addColumn("Motif");
     rmodel.addColumn("Sortie");
     rmodel.addColumn("Acquis");
     rmodel.addColumn("Autorisation");
     rmodel.addColumn("Categorie");
     rmodel.addColumn("Libelle");
     rmodel.addColumn("User");
     rtable.setRowHeight(30);
     rtable.setShowGrid(true);
     rtable.setGridColor(new Color(124,69,17));
     rtable.setSelectionBackground(new Color(124,69,17));
     try
     {
     stm = conn.obtenirconnexion().createStatement();
     ResultSet Rs = stm.executeQuery("Select * from depense");
     while(Rs.next())
     {
     rmodel.addRow(new Object[]
     {
     Rs.getString("id"),
     Rs.getString("montant"),
     Rs.getString("motif"),
     Rs.getString("datesortie"),
     Rs.getString("pouracqui"),
     Rs.getString("autorisation"),
     Rs.getString("refcategoriesortie"),
     Rs.getString("libelle"),
     Rs.getString("user")
     });
     }
     }
     catch(Exception e)
     {
     System.err.println(e);
     }
     rtable.setModel(rmodel);
     ChargerComboBox();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void ChargerComboBox() {
        try {
            stm = conn.obtenirconnexion().createStatement();
            String sql = "select * from categoriesortie";
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                txtcateg.addItem(rs.getString("designation"));
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
   
    private void getID() {
    try {
    stm = conn.obtenirconnexion().createStatement();
    String sql = "select id from categoriesortie where designation= '" + txtcateg.getSelectedItem() + "'";
    ResultSet rs = stm.executeQuery(sql);
    if (rs.next()) {
    String id = rs.getString("id");
    txtrefcateg.setText(id);
    }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, e);
    }
    }
    
    private void rajouter()
{
        String id = txtid.getText();
        String lemontant = txtmontant.getText();
        String lemotif = txtmotif.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd", Locale.ENGLISH);
        String ladate = dateFormat.format(txtdate.getDate());
        String pour = txtpourak.getText();
        String aut = txtaut.getText();
        String categ = txtcateg.getSelectedItem().toString();
        String refcateg = txtrefcateg.getText();
        String lib = txtlib.getText();
        String theuser = txtuser.getText();
        String requete = "insert into depense(montant,motif,datesortie,pouracqui,autorisation,refcategoriesortie,libelle,user) VALUES ('"+
        lemontant+"','"+
        lemotif+"','"+
        ladate+"','"+
        pour+"','"+
        aut+"','"+
        refcateg+"','"+
        lib+"','"+
        theuser+"')";
        try
        {
            stm = conn.obtenirconnexion().createStatement();
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Depense Ajoutee");
        }
        catch(SQLException | HeadlessException ex){JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());}
        rafficher();
}
     private void rdeplace(int i)
{
   try
   {
     txtid.setText(rmodel.getValueAt(i, 0).toString());
     txtmontant.setText(rmodel.getValueAt(i, 1).toString());
     txtmotif.setText(rmodel.getValueAt(i, 2).toString());
     txtpourak.setText(rmodel.getValueAt(i, 4).toString());
     txtaut.setText(rmodel.getValueAt(i, 5).toString());
     txtrefcateg.setText(rmodel.getValueAt(i, 6).toString());
     txtlib.setText(rmodel.getValueAt(i, 7).toString());
     txtuser.setText(rmodel.getValueAt(i, 8).toString());
     
   }
   catch(Exception e)
   {
       System.err.println(e);
       JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
   }
}
     private void rafficher()
{
 try
        {
        rmodel.setRowCount(0);
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from depense");
        while(Rs.next())
        {
            rmodel.addRow(new Object[]{
                    Rs.getString("id"),
                    Rs.getString("montant"),
                    Rs.getString("motif"),
                    Rs.getString("datesortie"),
                    Rs.getString("pouracqui"),
                    Rs.getString("autorisation"),
                    Rs.getString("refcategoriesortie"),
                    Rs.getString("libelle"),
                    Rs.getString("user")
            });
        }
        rrefresh();
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
        rtable.setModel(rmodel);
}
    private void rmodifier()
{
    try
        {
            if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        {
        String id = txtid.getText();
        String lemontant = txtmontant.getText();
        String lemotif = txtmotif.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd", Locale.ENGLISH);
        String ladate = dateFormat.format(txtdate.getDate());
        String pour = txtpourak.getText();
        String aut = txtaut.getText();
        String categ = txtcateg.getSelectedItem().toString();
        String refcateg = txtrefcateg.getText();
        String lib = txtlib.getText();
        String theuser = txtuser.getText();
            stm.executeUpdate("UPDATE depense SET montant='"
                    +lemontant+
                    "',motif='"+lemotif+
                    "',datesortie='"+ladate+
                    "',pouracqui='"+pour+
                    "',autorisation='"+aut+
                    "',refcategoriesortie='"+refcateg+
                    "',libelle='"+lib+
                    "',user='"+theuser+
                    "' WHERE id="+id);
            rafficher();
            rrefresh();
        }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Erreur de modification"+e.getMessage());
            System.err.println(e);
            rafficher();
        }
}
    private void rrefresh()
{
            txtid.setText("");
            txtmontant.setText("");
            txtpourak.setText("");
            txtlib.setText("");
            txtaut.setText("");
            txtmotif.setText("");
            txtrefcateg.setText("");
            txtlib.setText("");
            txtuser.setText("");
}
    private void rsupprimer()
    {
        try
        {
            if(JOptionPane.showConfirmDialog(null, "Attention, vous etes sur le point de supprimer cette cattegorie", "Supprimer la categorie", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            if(txtid.getText().length()!=0)
            {
                stm.executeUpdate("Delete From recette where id = "+txtid.getText());
                rafficher();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Veuillez remplir le champ id svp!!");
                rrefresh();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erreur de suppression"+e.getMessage());
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panbtn = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        panfiels = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtlib = new javax.swing.JTextField();
        txtmontant = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtmotif = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtcateg = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtrefcateg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtaut = new javax.swing.JTextField();
        txtpourak = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panmenu = new javax.swing.JPanel();
        ppancinq = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ppanquatre = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ppantrois = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ppanun = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ppandeux = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pbs = new javax.swing.JPanel();
        add1 = new javax.swing.JLabel();
        add2 = new javax.swing.JLabel();
        stxtide = new javax.swing.JLabel();
        add3 = new javax.swing.JLabel();
        add4 = new javax.swing.JLabel();
        add5 = new javax.swing.JLabel();
        add6 = new javax.swing.JLabel();
        add7 = new javax.swing.JLabel();
        stxtuser = new javax.swing.JLabel();
        stxtmontant = new javax.swing.JLabel();
        stxtpouracquis = new javax.swing.JLabel();
        stxtmotif = new javax.swing.JLabel();
        stxtcateg = new javax.swing.JLabel();
        stxtmontantenlettre3 = new javax.swing.JLabel();
        stxtdate = new javax.swing.JLabel();
        add8 = new javax.swing.JLabel();
        add9 = new javax.swing.JLabel();
        add10 = new javax.swing.JLabel();
        stxtaut = new javax.swing.JLabel();
        add11 = new javax.swing.JLabel();
        stxtlib = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panbtn.setBackground(new java.awt.Color(124, 69, 17));

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_add_32.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_edit_pie_chart_report_32.png"))); // NOI18N
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMouseClicked(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_trash_32.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_update_left_rotation_32.png"))); // NOI18N
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_print_32.png"))); // NOI18N
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panbtnLayout = new javax.swing.GroupLayout(panbtn);
        panbtn.setLayout(panbtnLayout);
        panbtnLayout.setHorizontalGroup(
            panbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panbtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(change)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refresh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(print, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panbtnLayout.setVerticalGroup(
            panbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 50, 210));

        panfiels.setBackground(new java.awt.Color(255, 255, 255));
        panfiels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(124, 69, 17));
        jLabel10.setText("ID");
        panfiels.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 11, -1, -1));

        txtid.setEditable(false);
        panfiels.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 34, 75, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(124, 69, 17));
        jLabel11.setText("LIBELLE");
        panfiels.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtlib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlibActionPerformed(evt);
            }
        });
        panfiels.add(txtlib, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 179, 32));
        panfiels.add(txtmontant, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 34, 152, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(124, 69, 17));
        jLabel12.setText("MOTIF");
        panfiels.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));
        panfiels.add(txtmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 179, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(124, 69, 17));
        jLabel13.setText("MONTANT");
        panfiels.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 11, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(124, 69, 17));
        jLabel14.setText("DATE");
        panfiels.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(124, 69, 17));
        jLabel15.setText("CATEGORIE");
        panfiels.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 72, -1, -1));
        panfiels.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 179, 32));

        txtcateg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtcategItemStateChanged(evt);
            }
        });
        txtcateg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcategMouseClicked(evt);
            }
        });
        panfiels.add(txtcateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(124, 69, 17));
        jLabel16.setText("ID CAT");
        panfiels.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 72, -1, -1));
        panfiels.add(txtrefcateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 97, 180, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(124, 69, 17));
        jLabel17.setText("USER");
        panfiels.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 133, -1, -1));
        panfiels.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 156, 152, 32));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(124, 69, 17));
        jLabel18.setText("AUTORISATION");
        panfiels.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 133, -1, -1));
        panfiels.add(txtaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 156, 180, 32));

        txtpourak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpourakActionPerformed(evt);
            }
        });
        panfiels.add(txtpourak, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 34, 101, 32));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(124, 69, 17));
        jLabel19.setText("POUR ACQUIT");
        panfiels.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 11, -1, -1));

        getContentPane().add(panfiels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 540, 210));

        jPanel1.setBackground(new java.awt.Color(124, 69, 17));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_cancel_16.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eglise Saint-Potache--System de gestion");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GESTION DEPENSES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(235, 235, 235)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 40));

        panmenu.setBackground(new java.awt.Color(124, 69, 17));
        panmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ppancinq.setBackground(new java.awt.Color(124, 69, 17));
        ppancinq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_cash_in_hand_32.png"))); // NOI18N
        jLabel6.setText("CATEGORIE DEPENSE");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        ppancinq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 40));

        panmenu.add(ppancinq, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 260, 60));

        ppanquatre.setBackground(new java.awt.Color(124, 69, 17));
        ppanquatre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_recieve_32.png"))); // NOI18N
        jLabel5.setText("CATEGORIE RECETTE");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        ppanquatre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        panmenu.add(ppanquatre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 60));

        ppantrois.setBackground(new java.awt.Color(198, 144, 93));
        ppantrois.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));
        ppantrois.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_donation_32.png"))); // NOI18N
        jLabel4.setText("DEPENSES");
        ppantrois.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        panmenu.add(ppantrois, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 60));

        ppanun.setBackground(new java.awt.Color(124, 69, 17));
        ppanun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_home_32.png"))); // NOI18N
        jLabel2.setText("  ACCUEIL");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        ppanun.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        panmenu.add(ppanun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 60));

        ppandeux.setBackground(new java.awt.Color(124, 69, 17));
        ppandeux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_receive_dollar_32.png"))); // NOI18N
        jLabel3.setText("RECETTES");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        ppandeux.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        panmenu.add(ppandeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 60));

        getContentPane().add(panmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, 990, 70));

        pbs.setBackground(new java.awt.Color(204, 204, 204));

        add1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add1.setForeground(new java.awt.Color(124, 69, 17));
        add1.setText("BON DE SORTIE CAISSE N°");
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
        });

        add2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add2.setForeground(new java.awt.Color(124, 69, 17));
        add2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add2.setText("EGLISE SAINT-POTACHE");
        add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add2MouseClicked(evt);
            }
        });

        stxtide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stxtide.setForeground(new java.awt.Color(124, 69, 17));
        stxtide.setText("0");
        stxtide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtideMouseClicked(evt);
            }
        });

        add3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add3.setForeground(new java.awt.Color(124, 69, 17));
        add3.setText("USER");
        add3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add3MouseClicked(evt);
            }
        });

        add4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add4.setForeground(new java.awt.Color(124, 69, 17));
        add4.setText("MONTANT($)");
        add4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add4MouseClicked(evt);
            }
        });

        add5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add5.setForeground(new java.awt.Color(124, 69, 17));
        add5.setText("POUR ACQUIT");
        add5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add5MouseClicked(evt);
            }
        });

        add6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add6.setForeground(new java.awt.Color(124, 69, 17));
        add6.setText("MOTIF");
        add6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add6MouseClicked(evt);
            }
        });

        add7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add7.setForeground(new java.awt.Color(124, 69, 17));
        add7.setText("CATEGORIE");
        add7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add7MouseClicked(evt);
            }
        });

        stxtuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtuser.setForeground(new java.awt.Color(124, 69, 17));
        stxtuser.setText("User");
        stxtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtuserMouseClicked(evt);
            }
        });

        stxtmontant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtmontant.setForeground(new java.awt.Color(124, 69, 17));
        stxtmontant.setText("Montant($)");
        stxtmontant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtmontantMouseClicked(evt);
            }
        });

        stxtpouracquis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtpouracquis.setForeground(new java.awt.Color(124, 69, 17));
        stxtpouracquis.setText("Pour acquit");
        stxtpouracquis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtpouracquisMouseClicked(evt);
            }
        });

        stxtmotif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtmotif.setForeground(new java.awt.Color(124, 69, 17));
        stxtmotif.setText("Motif");
        stxtmotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtmotifMouseClicked(evt);
            }
        });

        stxtcateg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtcateg.setForeground(new java.awt.Color(124, 69, 17));
        stxtcateg.setText("Categorie");
        stxtcateg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtcategMouseClicked(evt);
            }
        });

        stxtmontantenlettre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtmontantenlettre3.setForeground(new java.awt.Color(124, 69, 17));
        stxtmontantenlettre3.setText("Fait a Goma, le");
        stxtmontantenlettre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtmontantenlettre3MouseClicked(evt);
            }
        });

        stxtdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtdate.setForeground(new java.awt.Color(124, 69, 17));
        stxtdate.setText("date");
        stxtdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtdateMouseClicked(evt);
            }
        });

        add8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add8.setForeground(new java.awt.Color(124, 69, 17));
        add8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add8.setText("Caissier Principal");
        add8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add8MouseClicked(evt);
            }
        });

        add9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add9.setForeground(new java.awt.Color(124, 69, 17));
        add9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add9.setText("Que mabouche chante ta louange");
        add9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add9MouseClicked(evt);
            }
        });

        add10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add10.setForeground(new java.awt.Color(124, 69, 17));
        add10.setText("AUTORISATION");
        add10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add10MouseClicked(evt);
            }
        });

        stxtaut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtaut.setForeground(new java.awt.Color(124, 69, 17));
        stxtaut.setText("Autorisation");
        stxtaut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtautMouseClicked(evt);
            }
        });

        add11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add11.setForeground(new java.awt.Color(124, 69, 17));
        add11.setText("LIBELLE");
        add11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add11MouseClicked(evt);
            }
        });

        stxtlib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stxtlib.setForeground(new java.awt.Color(124, 69, 17));
        stxtlib.setText("Libelle");
        stxtlib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stxtlibMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pbsLayout = new javax.swing.GroupLayout(pbs);
        pbs.setLayout(pbsLayout);
        pbsLayout.setHorizontalGroup(
            pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbsLayout.createSequentialGroup()
                        .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pbsLayout.createSequentialGroup()
                                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pbsLayout.createSequentialGroup()
                                        .addComponent(add1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stxtide, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pbsLayout.createSequentialGroup()
                                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add5)
                                    .addComponent(add4)
                                    .addComponent(add3)
                                    .addComponent(add6)
                                    .addComponent(add7)
                                    .addComponent(add10))
                                .addGap(24, 24, 24)
                                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stxtcateg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stxtmotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stxtuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stxtmontant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stxtpouracquis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stxtaut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbsLayout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(add9, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(pbsLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbsLayout.createSequentialGroup()
                        .addComponent(stxtmontantenlettre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stxtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pbsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add11)
                .addGap(79, 79, 79)
                .addComponent(stxtlib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbsLayout.setVerticalGroup(
            pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stxtide, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(stxtuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add4)
                    .addComponent(stxtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stxtpouracquis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add6)
                    .addComponent(stxtmotif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add7)
                    .addComponent(stxtcateg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add10)
                    .addComponent(stxtaut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add11)
                    .addComponent(stxtlib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stxtmontantenlettre3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stxtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add8)
                .addGap(18, 18, 18)
                .addComponent(add9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 330, 410));

        rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 600, 190));

        jLabel1.setBackground(new java.awt.Color(124, 69, 17));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/SmartSelect_20220407-093006_Opera Mini.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, -1, 570));

        setSize(new java.awt.Dimension(969, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Pconnexion access = new Pconnexion();
       access.quit();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       Pdepenses.super.dispose();
       Precettes open = new Precettes();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Pdepenses.super.dispose();
       Paccueil open = new Paccueil();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtlibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibActionPerformed

    private void txtcategItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtcategItemStateChanged
        getID();
    }//GEN-LAST:event_txtcategItemStateChanged

    private void txtcategMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcategMouseClicked
        getID();
    }//GEN-LAST:event_txtcategMouseClicked

    private void rtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtableMouseClicked
        try
        {
            int i=rtable.getSelectedRow();rdeplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Erreur de deplacement"+e.getLocalizedMessage());}
        
        try{
            conn.obtenirconnexion().createStatement();
            Rs = stm.executeQuery("select * from depense where id = "+txtid.getText());
            if(Rs.next()){
                String stxtid = Rs.getString("id");
                String stxtusers= Rs.getString("user");
                String stxtmontants = Rs.getString("montant");
                String stxtmotifs = Rs.getString("motif");
                String txtpouracquis = Rs.getString("pouracqui");
                String txtauts = Rs.getString("autorisation");
                String txtlibelle = Rs.getString("libelle");
                String txtcategs = Rs.getString("refcategoriesortie");
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMMMMMM yyyy");
                String txtdates= dateFormat.format(Rs.getDate("datesortie"));
                
                stxtide.setText(""+stxtid);
                stxtuser.setText(":"+stxtusers);
                stxtmontant.setText(":"+stxtmontants+"$");
                stxtmotif.setText(":"+stxtmotifs);
                stxtpouracquis.setText(":"+txtpouracquis);
                stxtaut.setText(":"+txtauts);
                stxtlib.setText(":"+txtlibelle);
                stxtcateg.setText(":"+txtcategs);
                stxtdate.setText(":"+txtdates);
            }
           
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_rtableMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
          // TODO add your handling code here:
        rajouter();
        rafficher();
        rrefresh();
    }//GEN-LAST:event_addMouseClicked

    private void changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseClicked
        // TODO add your handling code here:
        rmodifier();
        rafficher();
        rrefresh();
    }//GEN-LAST:event_changeMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        rsupprimer();
        rafficher();
        rrefresh();
    }//GEN-LAST:event_deleteMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        rrefresh();
    }//GEN-LAST:event_refreshMouseClicked

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add1MouseClicked

    private void add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add2MouseClicked

    private void stxtideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtideMouseClicked

    private void add3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add3MouseClicked

    private void add4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add4MouseClicked

    private void add5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add5MouseClicked

    private void add6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add6MouseClicked

    private void add7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add7MouseClicked

    private void stxtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtuserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtuserMouseClicked

    private void stxtmontantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtmontantMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtmontantMouseClicked

    private void stxtpouracquisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtpouracquisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtpouracquisMouseClicked

    private void stxtmotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtmotifMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtmotifMouseClicked

    private void stxtcategMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtcategMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtcategMouseClicked

    private void stxtmontantenlettre3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtmontantenlettre3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtmontantenlettre3MouseClicked

    private void stxtdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtdateMouseClicked

    private void add8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add8MouseClicked

    private void add9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add9MouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
       Toolkit kit = Toolkit.getDefaultToolkit();
       PrintJob printer = kit.getPrintJob(this, "Print", null);
       Graphics graphics = printer.getGraphics();
       pbs.printAll(graphics);
       printer.end();
    }//GEN-LAST:event_printMouseClicked

    private void add10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add10MouseClicked

    private void stxtautMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtautMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtautMouseClicked

    private void add11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add11MouseClicked

    private void stxtlibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stxtlibMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtlibMouseClicked

    private void txtpourakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpourakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpourakActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       Pdepenses.super.dispose();
       PCrecettes open  = new PCrecettes();
       open.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Pdepenses.super.dispose();
        PCdepenses open = new PCdepenses();
        open.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pdepenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pdepenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel add1;
    private javax.swing.JLabel add10;
    private javax.swing.JLabel add11;
    private javax.swing.JLabel add2;
    private javax.swing.JLabel add3;
    private javax.swing.JLabel add4;
    private javax.swing.JLabel add5;
    private javax.swing.JLabel add6;
    private javax.swing.JLabel add7;
    private javax.swing.JLabel add8;
    private javax.swing.JLabel add9;
    private javax.swing.JLabel change;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panbtn;
    private javax.swing.JPanel panfiels;
    private javax.swing.JPanel panmenu;
    private javax.swing.JPanel pbs;
    private javax.swing.JPanel ppancinq;
    private javax.swing.JPanel ppandeux;
    private javax.swing.JPanel ppanquatre;
    private javax.swing.JPanel ppantrois;
    private javax.swing.JPanel ppanun;
    private javax.swing.JLabel print;
    private javax.swing.JLabel refresh;
    private javax.swing.JTable rtable;
    private javax.swing.JLabel stxtaut;
    private javax.swing.JLabel stxtcateg;
    private javax.swing.JLabel stxtdate;
    private javax.swing.JLabel stxtide;
    private javax.swing.JLabel stxtlib;
    private javax.swing.JLabel stxtmontant;
    private javax.swing.JLabel stxtmontantenlettre3;
    private javax.swing.JLabel stxtmotif;
    private javax.swing.JLabel stxtpouracquis;
    private javax.swing.JLabel stxtuser;
    private javax.swing.JTextField txtaut;
    private javax.swing.JComboBox txtcateg;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlib;
    private javax.swing.JTextField txtmontant;
    private javax.swing.JTextField txtmotif;
    private javax.swing.JTextField txtpourak;
    private javax.swing.JTextField txtrefcateg;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
